name: TEMP - Regenerate default snapshot

on:
  workflow_dispatch:

jobs:
  regen-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v3
        with:
          version: "25.10.4"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v2
        with:
          version: "0.9.4"

      - name: Run nf-test with --update-snapshot
        run: |
          nf-test test tests/default.nf.test --profile=+docker --update-snapshot --verbose
        continue-on-error: true

      - name: Show git diff
        run: git diff -- tests/default.nf.test.snap | head -c 200000

      - name: Upload regenerated snapshot
        uses: actions/upload-artifact@v4
        with:
          name: default-nf-test-snap
          path: tests/default.nf.test.snap
          retention-days: 3
